class_name DataForestBuilder
extends ZoneBuilderBase
## Builds the Data Forest's scenery procedurally and deterministically:
##   rolling forest floor with a lake basin, paths between the Ranger Camp,
##   Crystal Lake, Old Ruins and the Gateway home; crystal trees, glowing
##   mushrooms, mossy rocks, grass, fireflies and digital landmarks.
## Gameplay objects (NPCs, spawners, portal, pickups…) live in the .tscn,
## generated by tools/build_data_forest_scene.gd.

const SIZE := 200.0
const CELL := 2.0
const PLAY_RADIUS := 66.0

const CAMP := Vector2(-22, 22)
const CAMP_RADIUS := 9.0
const LAKE := Vector2(4, -30)
const LAKE_RADIUS := 13.0
const LAKE_DEPTH := 2.2
const WATER_Y := -0.55
const RUINS := Vector2(40, 6)
const RUINS_RADIUS := 12.0
const PORTAL := Vector2(-46, 46)
const GROVES := [[Vector2(18, 36), Vector2(13, 9)], [Vector2(-42, -12), Vector2(9, 10)]]
const HILLS := [[Vector2(-10, -54), 16.0, 5.0], [Vector2(54, -32), 13.0, 4.0], [Vector2(-58, 8), 11.0, 3.0],
	[Vector2(48, 44), 12.0, 3.0]]
const FLAT_ZONES := [[CAMP, 10.0, 0.05], [RUINS, 13.0, 0.3], [PORTAL, 7.0, 0.1]]
const FOREST_ZONES := [[Vector2(-50, -40), 20.0], [Vector2(-8, 52), 14.0], [Vector2(56, -8), 12.0],
	[Vector2(30, -52), 14.0], [Vector2(-56, 28), 12.0], [Vector2(-22, -30), 10.0]]

var _noise := FastNoiseLite.new()
var _detail := FastNoiseLite.new()


func _init() -> void:
	seed_value = 20251031
	terrain_size = SIZE
	terrain_cell = CELL
	play_radius = PLAY_RADIUS
	decorative_nodes = ["Grass", "Fireflies", "LilyPads", "SmallMushrooms"]
	_noise.seed = 21
	_noise.frequency = 0.032
	_noise.fractal_octaves = 3
	_detail.seed = 5
	_detail.frequency = 0.11
	paths = [
		PackedVector2Array([Vector2(-44, 44), Vector2(-34, 34), Vector2(-26, 26)]),
		PackedVector2Array([Vector2(-18, 16), Vector2(-10, 4), Vector2(-4, -8), Vector2(0, -15)]),
		PackedVector2Array([Vector2(-14, 22), Vector2(0, 18), Vector2(14, 14), Vector2(29, 8)]),
		PackedVector2Array([Vector2(0, 18), Vector2(10, 27)]),
		PackedVector2Array([Vector2(-27, 15), Vector2(-34, 2), Vector2(-38, -4)]),
	]


func _build_scenery() -> void:
	_build_lake()
	_build_camp()
	_build_ruins()
	_build_portal_area()
	_build_trees()
	_build_mushrooms()
	_build_rocks()
	_build_grass()
	_build_fireflies()
	_data_cubes([CAMP, LAKE, RUINS, PORTAL, Vector2(-10, -54), Vector2(50, 44)], 8,
		[Color(0.35, 1.0, 0.8), Color(0.75, 0.55, 1.0), Color(1.0, 0.6, 0.85)])
	_sky_islands(5, Color("4fb88a"), Color("6a5a8e"))


# ---------------------------------------------------------------------------
# Height field
# ---------------------------------------------------------------------------

func get_height(x: float, z: float) -> float:
	var p := Vector2(x, z)
	var h := _noise.get_noise_2d(x, z) * 0.8 + _detail.get_noise_2d(x, z) * 0.15
	var r := p.length()
	h += smoothstep(PLAY_RADIUS - 6.0, PLAY_RADIUS + 20.0, r) * (16.0 + _noise.get_noise_2d(x * 2.0, z * 2.0) * 6.0)
	for hill in HILLS:
		var d := p.distance_to(hill[0])
		if d < hill[1]:
			h += hill[2] * smoothstep(hill[1], 0.0, d)
	for zone in FLAT_ZONES:
		var d := p.distance_to(zone[0])
		if d < zone[1] + 4.0:
			h = lerpf(h, zone[2], 1.0 - smoothstep(zone[1], zone[1] + 4.0, d))
	var path_d := distance_to_paths(p)
	if path_d < 5.0:
		h = lerpf(h, minf(h, 0.05) * 0.3, 1.0 - smoothstep(2.5, 5.0, path_d))
	var lake_d := p.distance_to(LAKE)
	h = lerpf(h, -LAKE_DEPTH, 1.0 - smoothstep(LAKE_RADIUS - 3.0, LAKE_RADIUS + 1.5, lake_d))
	return h


func _ground_color(x: float, z: float, h: float) -> Color:
	var p := Vector2(x, z)
	var n := _noise.get_noise_2d(x * 1.7 + 40.0, z * 1.7)
	var c := Color("2f8a4f").lerp(Color("4ea85f"), clampf(n * 0.9 + 0.5, 0.0, 1.0))
	for grove in GROVES:
		var gd := _box_distance(p, grove[0], grove[1])
		if gd < 3.0:
			c = c.lerp(Color("25774a"), 1.0 - smoothstep(0.0, 3.0, gd))
	c = c.lerp(Color("2f6f4f"), smoothstep(2.0, 6.0, h))
	c = c.lerp(Color("7f86a8"), smoothstep(7.0, 13.0, h))
	c = c.lerp(Color("c2ad86"), 1.0 - smoothstep(1.8, 3.2, distance_to_paths(p)))
	var camp_d := p.distance_to(CAMP)
	if camp_d < CAMP_RADIUS + 2.0:
		c = c.lerp(Color("b89f78"), 1.0 - smoothstep(CAMP_RADIUS - 1.5, CAMP_RADIUS + 2.0, camp_d))
	var ruins_d := p.distance_to(RUINS)
	if ruins_d < RUINS_RADIUS + 2.0:
		c = c.lerp(Color("a9a3b8"), 1.0 - smoothstep(RUINS_RADIUS - 1.0, RUINS_RADIUS + 2.0, ruins_d))
	var lake_d := p.distance_to(LAKE)
	if lake_d < LAKE_RADIUS + 3.0:
		c = c.lerp(Color("cbbd8c"), 1.0 - smoothstep(LAKE_RADIUS + 0.5, LAKE_RADIUS + 3.0, lake_d))
	if h < -0.8:
		c = c.lerp(Color("2a6f8a"), smoothstep(-0.8, -1.6, h))
	return c


# ---------------------------------------------------------------------------
# Landmarks
# ---------------------------------------------------------------------------

func _build_lake() -> void:
	var lake := Node3D.new()
	lake.name = "CrystalLake"
	lake.position = Vector3(LAKE.x, 0.0, LAKE.y)
	add_child(lake)
	var water := MeshInstance3D.new()
	water.name = "Water"
	var disc := CylinderMesh.new()
	disc.top_radius = LAKE_RADIUS + 1.2
	disc.bottom_radius = LAKE_RADIUS + 1.2
	disc.height = 0.02
	disc.radial_segments = 48
	disc.rings = 1
	water.mesh = disc
	var mat := ShaderMaterial.new()
	mat.shader = load("res://shaders/water.gdshader")
	mat.set_shader_parameter("deep_color", Color(0.12, 0.3, 0.62))
	mat.set_shader_parameter("shallow_color", Color(0.35, 0.85, 0.9))
	mat.set_shader_parameter("flow_speed", 0.06)
	water.material_override = mat
	water.position = Vector3(0, WATER_Y, 0)
	water.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	lake.add_child(water)
	# Invisible barrier: the lake is scenery, not walkable.
	var body := StaticBody3D.new()
	body.name = "LakeBarrier"
	body.collision_layer = 1
	lake.add_child(body)
	_add_cylinder_shape(body, Vector3(0, 0.5, 0), LAKE_RADIUS - 0.6, 5.0)
	# Crystal spires rising from the water.
	for i in 5:
		var ang := i * TAU / 5.0 + 0.5
		var d := _rng.randf_range(2.0, LAKE_RADIUS - 4.0)
		var s := _rng.randf_range(1.2, 2.6)
		var spire := MeshKit.part(lake, MeshKit.prism(), MeshKit.toon(Color("7fe8ff"), {"emission": 0.7}),
			Vector3(cos(ang) * d, WATER_Y + s * 1.2, sin(ang) * d), Vector3(s * 0.7, s * 2.8, s * 0.7),
			Vector3(_rng.randf_range(-12, 12), _rng.randf() * 180.0, _rng.randf_range(-12, 12)))
		spire.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	# Lily pads (decorative).
	var pads: Array[Transform3D] = []
	var pad_colors: Array[Color] = []
	for i in 26:
		var ang := _rng.randf() * TAU
		var d := _rng.randf_range(LAKE_RADIUS * 0.45, LAKE_RADIUS - 0.5)
		var s := _rng.randf_range(0.5, 0.9)
		pads.append(Transform3D(Basis().scaled(Vector3(s, 0.03, s)), Vector3(LAKE.x + cos(ang) * d, WATER_Y + 0.03, LAKE.y + sin(ang) * d)))
		pad_colors.append(Color("4fc27a").lerp(Color("7ee08f"), _rng.randf()))
	_multimesh("LilyPads", MeshKit.cylinder(), pads, pad_colors, _vertex_color_material(), false)
	_occupy(LAKE, LAKE_RADIUS + 2.5)


func _build_camp() -> void:
	var camp := Node3D.new()
	camp.name = "RangerCamp"
	camp.position = Vector3(CAMP.x, get_height(CAMP.x, CAMP.y), CAMP.y)
	add_child(camp)
	var body := StaticBody3D.new()
	body.collision_layer = 1
	camp.add_child(body)
	# Layout keeps the four path mouths clear (0°, 135°, 234°, 304° from the
	# camp centre): tent south, shop counter north, terminal west (scene).
	var tent_pos := Vector3(0, 0, -6.5)
	var canvas := MeshKit.toon(Color("e9a15a"))
	MeshKit.part(camp, MeshKit.prism(), canvas, tent_pos + Vector3(0, 1.2, 0), Vector3(3.2, 2.4, 3.0))
	MeshKit.part(camp, MeshKit.prism(), MeshKit.toon(Color("6b3f22")), tent_pos + Vector3(0, 0.75, 0.02), Vector3(1.0, 1.5, 3.04))
	_add_box_shape(body, tent_pos + Vector3(0, 1.0, 0), Vector3(2.8, 2.0, 2.8))
	# Campfire with log seats.
	var stone := MeshKit.toon(Color("8d93a8"))
	for i in 8:
		var ang := i * TAU / 8.0
		MeshKit.part(camp, MeshKit.sphere_low(), stone, Vector3(cos(ang) * 0.9, 0.12, sin(ang) * 0.9), Vector3(0.36, 0.26, 0.36))
	MeshKit.part(camp, MeshKit.cone(), MeshKit.toon(Color("ff9a3d"), {"emission": 2.2}), Vector3(0, 0.55, 0), Vector3(0.7, 1.0, 0.7))
	MeshKit.part(camp, MeshKit.cone(), MeshKit.toon(Color("ffe066"), {"emission": 2.6}), Vector3(0, 0.45, 0), Vector3(0.4, 0.7, 0.4))
	_add_cylinder_shape(body, Vector3(0, 0.4, 0), 1.1, 0.8)
	var wood := MeshKit.toon(Color("8a5a36"))
	for ang in [0.6, 2.4, 4.3]:
		var p := Vector3(cos(ang), 0, sin(ang)) * 2.6
		var log_mi := MeshKit.part(camp, MeshKit.cylinder(), wood, p + Vector3(0, 0.28, 0), Vector3(0.5, 1.8, 0.5), Vector3(90, 0, 0))
		log_mi.rotation.y = -ang
	# Shop counter with awning, facing the fire (Lumi stands behind it).
	var counter := Node3D.new()
	counter.name = "ShopCounter"
	counter.position = Vector3(-0.8, 0, 5.2)
	counter.rotation.y = atan2(0.8, -5.2)
	camp.add_child(counter)
	MeshKit.part(counter, MeshKit.box(), MeshKit.toon(Color("b07a4a")), Vector3(0, 0.5, 0), Vector3(2.6, 1.0, 0.8))
	MeshKit.part(counter, MeshKit.box(), MeshKit.toon(Color("9a6a40")), Vector3(0, 1.04, 0), Vector3(2.8, 0.1, 1.0))
	for x in [-1.3, 1.3]:
		MeshKit.part(counter, MeshKit.cylinder(), wood, Vector3(x, 1.4, -1.6), Vector3(0.12, 2.8, 0.12))
	MeshKit.part(counter, MeshKit.box(), MeshKit.toon(Color("5ac86e")), Vector3(0, 2.8, -1.0), Vector3(3.0, 0.08, 1.6), Vector3(-12, 0, 0))
	for i in 3:
		MeshKit.part(counter, MeshKit.box(), MeshKit.toon([Color("ff7a45"), Color("34c3ff"), Color("ffd166")][i]),
			Vector3(-0.8 + i * 0.8, 1.25, 0.05), Vector3(0.36, 0.3, 0.36))
	var counter_body := StaticBody3D.new()
	counter_body.collision_layer = 1
	counter.add_child(counter_body)
	_add_box_shape(counter_body, Vector3(0, 0.6, 0), Vector3(2.8, 1.2, 1.0))
	# Supply crates beside the counter and lamps between the paths.
	for p in [Vector3(2.5, 0, 6.5), Vector3(3.4, 0, 7.3)]:
		MeshKit.part(camp, MeshKit.box(), MeshKit.toon(Color("a36e42")), p + Vector3(0, 0.4, 0), Vector3(0.8, 0.8, 0.8), Vector3(0, 20, 0))
		_add_box_shape(body, p + Vector3(0, 0.4, 0), Vector3(0.8, 0.8, 0.8))
	for deg in [30.0, 160.0, 210.0, 330.0]:
		var ang := deg_to_rad(deg)
		_lamp(camp, Vector3(cos(ang), 0, sin(ang)) * (CAMP_RADIUS - 0.5), Color("7dffc8"))
	_occupy(CAMP, CAMP_RADIUS + 1.5)


func _build_ruins() -> void:
	var ruins := Node3D.new()
	ruins.name = "OldRuins"
	ruins.position = Vector3(RUINS.x, get_height(RUINS.x, RUINS.y), RUINS.y)
	add_child(ruins)
	var body := StaticBody3D.new()
	body.collision_layer = 1
	ruins.add_child(body)
	var stone := MeshKit.toon(Color("b3adc4"))
	var dark := MeshKit.toon(Color("8a84a0"))
	var moss := MeshKit.toon(Color("5fae78"))
	# Cracked floor slabs.
	for ix in range(-4, 5):
		for iz in range(-4, 5):
			var local := Vector2(ix, iz) * 2.2
			if local.length() > RUINS_RADIUS - 2.0 or _rng.randf() < 0.18:
				continue
			var tilt := Vector3(_rng.randf_range(-2, 2), _rng.randf() * 6.0, _rng.randf_range(-2, 2))
			var tile := MeshKit.part(ruins, MeshKit.box(), stone if (ix + iz) % 2 == 0 else dark,
				Vector3(local.x, 0.05, local.y), Vector3(2.05, 0.18, 2.05), tilt)
			tile.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	# Ring of pillars, some broken; the west side (path) stays open.
	var count := 12
	for i in count:
		var ang := i * TAU / count
		var dir := Vector2(cos(ang), sin(ang))
		if dir.dot(Vector2(-1, 0.1).normalized()) > 0.92:
			continue
		var pos := Vector3(dir.x, 0, dir.y) * (RUINS_RADIUS - 2.5)
		var broken := _rng.randf() < 0.4
		var height := _rng.randf_range(1.2, 2.2) if broken else _rng.randf_range(3.6, 4.6)
		MeshKit.part(ruins, MeshKit.cylinder(), stone, pos + Vector3(0, height * 0.5, 0), Vector3(0.9, height, 0.9))
		MeshKit.part(ruins, MeshKit.box(), dark, pos + Vector3(0, 0.15, 0), Vector3(1.3, 0.3, 1.3))
		if not broken:
			MeshKit.part(ruins, MeshKit.box(), dark, pos + Vector3(0, height + 0.12, 0), Vector3(1.2, 0.24, 1.2))
		MeshKit.part(ruins, MeshKit.sphere_low(), moss, pos + Vector3(0.2, height * 0.35, 0.25), Vector3(0.55, 0.4, 0.45))
		_add_cylinder_shape(body, pos + Vector3(0, height * 0.5, 0), 0.5, height)
		if broken and _rng.randf() < 0.7:
			var fallen := pos * 0.82 + Vector3(_rng.randf_range(-1, 1), 0.35, _rng.randf_range(-1, 1))
			MeshKit.part(ruins, MeshKit.cylinder(), stone, fallen, Vector3(0.8, 1.8, 0.8), Vector3(90, _rng.randf() * 180.0, 0))
	# Entrance arch facing the path (west).
	for side in [-1.0, 1.0]:
		MeshKit.part(ruins, MeshKit.box(), stone, Vector3(-RUINS_RADIUS + 1.5, 2.2, side * 2.4), Vector3(1.0, 4.4, 1.0))
		_add_box_shape(body, Vector3(-RUINS_RADIUS + 1.5, 2.2, side * 2.4), Vector3(1.0, 4.4, 1.0))
	MeshKit.part(ruins, MeshKit.box(), dark, Vector3(-RUINS_RADIUS + 1.5, 4.6, 0), Vector3(1.2, 0.6, 6.0))
	MeshKit.part(ruins, MeshKit.sphere(), MeshKit.toon(Color("b28dff"), {"emission": 1.6}), Vector3(-RUINS_RADIUS + 0.9, 4.6, 0), Vector3(0.5, 0.5, 0.5))
	# Central "ancient server" monolith with a holographic column.
	MeshKit.part(ruins, MeshKit.box(), MeshKit.toon(Color("3a3f6b")), Vector3(0, 1.6, 0), Vector3(1.6, 3.2, 1.0))
	for k in 4:
		MeshKit.part(ruins, MeshKit.box(), MeshKit.toon(Color("b28dff"), {"emission": 1.8}), Vector3(0, 0.6 + k * 0.7, 0.51),
			Vector3(1.1, 0.08, 0.02))
	_add_box_shape(body, Vector3(0, 1.6, 0), Vector3(1.6, 3.2, 1.0))
	_occupy(RUINS, RUINS_RADIUS + 1.5)
	_data_pillar(Vector3(RUINS.x + 7.0, get_height(RUINS.x + 7.0, RUINS.y - 16.0), RUINS.y - 16.0), 10.0, Color(0.72, 0.5, 1.0))


func _build_portal_area() -> void:
	for p in [Vector2(-53, 40), Vector2(-40, 53)]:
		_data_pillar(Vector3(p.x, get_height(p.x, p.y), p.y), 11.0, Color(0.72, 0.5, 1.0))
	_occupy(PORTAL, 7.0)


# ---------------------------------------------------------------------------
# Scatter (MultiMesh)
# ---------------------------------------------------------------------------

func _is_clear(p: Vector2, radius: float, path_margin := 4.0) -> bool:
	if p.length() > PLAY_RADIUS + 14.0:
		return false
	if distance_to_paths(p) < path_margin + radius:
		return false
	return not _is_occupied(p, radius)


func _in_grove(p: Vector2, margin := 0.0) -> bool:
	for grove in GROVES:
		if _box_distance(p, grove[0], grove[1]) < margin:
			return true
	return false


func _forest_density(p: Vector2) -> float:
	var density := 0.16
	for zone in FOREST_ZONES:
		var d := p.distance_to(zone[0])
		if d < zone[1]:
			density = maxf(density, 0.9 * smoothstep(zone[1], zone[1] * 0.3, d))
	if p.length() > PLAY_RADIUS - 4.0:
		density = maxf(density, 0.6)
	if _in_grove(p, 2.0):
		density = 0.0
	return density


func _build_trees() -> void:
	var trunks: Array[Transform3D] = []
	var leafy: Array[Transform3D] = []
	var leafy_colors: Array[Color] = []
	var crystals: Array[Transform3D] = []
	var crystal_colors: Array[Color] = []
	var body := StaticBody3D.new()
	body.name = "TreeColliders"
	body.collision_layer = 1
	add_child(body)
	var crystal_palette := [Color("5ff0d0"), Color("7fb8ff"), Color("b28dff"), Color("ff9ad5")]
	var step := 5.0
	var x := -90.0
	while x <= 90.0:
		var z := -90.0
		while z <= 90.0:
			var p := Vector2(x + _rng.randf_range(-2.2, 2.2), z + _rng.randf_range(-2.2, 2.2))
			z += step
			if _rng.randf() > _forest_density(p) or not _is_clear(p, 1.6, 3.5):
				continue
			var h := get_height(p.x, p.y)
			var s := _rng.randf_range(0.85, 1.4)
			var yaw := _rng.randf() * TAU
			trunks.append(Transform3D(Basis(Vector3.UP, yaw).scaled(Vector3(0.42 * s, 2.2 * s, 0.42 * s)), Vector3(p.x, h + 1.1 * s, p.y)))
			if _rng.randf() < 0.45:
				# Crystal tree: tall faceted canopy that softly glows.
				crystals.append(Transform3D(Basis(Vector3.UP, yaw).scaled(Vector3(2.2, 4.2, 2.2) * s), Vector3(p.x, h + 3.9 * s, p.y)))
				crystal_colors.append(crystal_palette[_rng.randi() % crystal_palette.size()])
			else:
				leafy.append(Transform3D(Basis(Vector3.UP, yaw).scaled(Vector3(3.0, 2.5, 3.0) * s), Vector3(p.x, h + 3.2 * s, p.y)))
				leafy_colors.append(Color("2f9d6e").lerp(Color("5cc98a"), _rng.randf()))
			if p.length() < PLAY_RADIUS + 4.0:
				_add_cylinder_shape(body, Vector3(p.x, h + 1.5, p.y), 0.45 * s, 3.0)
			_occupy(p, 1.6 * s)
		x += step
	_multimesh("Trunks", MeshKit.cylinder(), trunks, [], MeshKit.toon(Color("5a4a6e")))
	_multimesh("LeafyCanopies", MeshKit.sphere_low(), leafy, leafy_colors, _vertex_color_material())
	var crystal_mat := ShaderMaterial.new()
	crystal_mat.shader = load("res://shaders/crystal_glow.gdshader")
	_multimesh("CrystalCanopies", _crystal_mesh(), crystals, crystal_colors, crystal_mat)


## Low-poly double pyramid used for crystal canopies.
func _crystal_mesh() -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var ring: Array[Vector3] = []
	for i in 6:
		var ang := i * TAU / 6.0
		ring.append(Vector3(cos(ang) * 0.5, 0.0, sin(ang) * 0.5))
	var top := Vector3(0, 0.62, 0)
	var bottom := Vector3(0, -0.38, 0)
	for i in 6:
		var a := ring[i]
		var b := ring[(i + 1) % 6]
		for tri in [[top, b, a], [bottom, a, b]]:
			var n: Vector3 = (tri[1] - tri[0]).cross(tri[2] - tri[0]).normalized()
			for v in tri:
				st.set_normal(n)
				st.add_vertex(v)
	return st.commit()


func _build_mushrooms() -> void:
	var stems: Array[Transform3D] = []
	var caps: Array[Transform3D] = []
	var cap_colors: Array[Color] = []
	var body := StaticBody3D.new()
	body.name = "MushroomColliders"
	body.collision_layer = 1
	add_child(body)
	var palette := [Color("ff7ac8"), Color("7af0ff"), Color("c49bff"), Color("ffd166")]
	# Giant landmark mushrooms (with collision).
	var placed := 0
	var attempts := 0
	while placed < 14 and attempts < 400:
		attempts += 1
		var p := Vector2(_rng.randf_range(-60, 60), _rng.randf_range(-60, 60))
		if not _is_clear(p, 1.8, 3.0):
			continue
		var h := get_height(p.x, p.y)
		var s := _rng.randf_range(1.6, 2.6)
		stems.append(Transform3D(Basis().scaled(Vector3(0.35, 1.3, 0.35) * s), Vector3(p.x, h + 0.65 * s, p.y)))
		caps.append(Transform3D(Basis().scaled(Vector3(1.5, 0.8, 1.5) * s), Vector3(p.x, h + 1.3 * s, p.y)))
		cap_colors.append(palette[_rng.randi() % palette.size()])
		_add_cylinder_shape(body, Vector3(p.x, h + 1.0, p.y), 0.2 * s, 2.0)
		_occupy(p, 1.2 * s)
		placed += 1
	var stem_mat := MeshKit.toon(Color("efe6d8"))
	var cap_mat := ShaderMaterial.new()
	cap_mat.shader = load("res://shaders/crystal_glow.gdshader")
	cap_mat.set_shader_parameter("glow", 0.8)
	_multimesh("GiantMushroomStems", MeshKit.cylinder(), stems, [], stem_mat)
	_multimesh("GiantMushroomCaps", MeshKit.hemisphere(), caps, cap_colors, cap_mat)
	# Small clusters (decorative, no collision).
	var small_stems: Array[Transform3D] = []
	var small_caps: Array[Transform3D] = []
	var small_colors: Array[Color] = []
	for i in 260:
		var p := Vector2(_rng.randf_range(-64, 64), _rng.randf_range(-64, 64))
		if _forest_density(p) < 0.3 or not _is_clear(p, 0.2, 2.0):
			continue
		var h := get_height(p.x, p.y)
		var s := _rng.randf_range(0.18, 0.35)
		small_stems.append(Transform3D(Basis().scaled(Vector3(0.3, 1.2, 0.3) * s), Vector3(p.x, h + 0.6 * s, p.y)))
		small_caps.append(Transform3D(Basis().scaled(Vector3(1.4, 0.8, 1.4) * s), Vector3(p.x, h + 1.2 * s, p.y)))
		small_colors.append(palette[_rng.randi() % palette.size()])
	var small := Node3D.new()
	small.name = "SmallMushrooms"
	add_child(small)
	var stems_mm := _multimesh("Stems", MeshKit.cylinder(), small_stems, [], stem_mat, false)
	var caps_mm := _multimesh("Caps", MeshKit.hemisphere(), small_caps, small_colors, cap_mat, false)
	for mm in [stems_mm, caps_mm]:
		mm.reparent(small, false)


func _build_rocks() -> void:
	var rocks: Array[Transform3D] = []
	var colors: Array[Color] = []
	var body := StaticBody3D.new()
	body.name = "RockColliders"
	body.collision_layer = 1
	add_child(body)
	var placed := 0
	var attempts := 0
	while placed < 55 and attempts < 600:
		attempts += 1
		var p := Vector2(_rng.randf_range(-78, 78), _rng.randf_range(-78, 78))
		if not _is_clear(p, 1.0, 3.0):
			continue
		var h := get_height(p.x, p.y)
		var big := _rng.randf() < 0.3
		var s := _rng.randf_range(1.2, 2.3) if big else _rng.randf_range(0.35, 0.8)
		var basis := Basis.from_euler(Vector3(_rng.randf() * 0.6, _rng.randf() * TAU, _rng.randf() * 0.6)).scaled(Vector3(s * 1.2, s * 0.8, s))
		rocks.append(Transform3D(basis, Vector3(p.x, h + s * 0.2, p.y)))
		colors.append(Color("8d93a8").lerp(Color("6fa888"), _rng.randf() * 0.6))
		if big and p.length() < PLAY_RADIUS + 4.0:
			var shape := CollisionShape3D.new()
			var sphere := SphereShape3D.new()
			sphere.radius = s * 0.55
			shape.shape = sphere
			shape.position = Vector3(p.x, h + s * 0.2, p.y)
			body.add_child(shape)
		_occupy(p, s * 0.6)
		placed += 1
	_multimesh("Rocks", MeshKit.sphere_low(), rocks, colors, _vertex_color_material())


func _build_grass() -> void:
	var tuft := _make_tuft_mesh()
	var grass: Array[Transform3D] = []
	var grass_colors: Array[Color] = []
	var tall: Array[Transform3D] = []
	var tall_colors: Array[Color] = []
	for i in 1100:
		var p := Vector2(_rng.randf_range(-66, 66), _rng.randf_range(-66, 66))
		if not _is_clear(p, 0.2, 2.2):
			continue
		var s := _rng.randf_range(0.5, 1.0)
		grass.append(Transform3D(Basis(Vector3.UP, _rng.randf() * TAU).scaled(Vector3(s, s, s)), Vector3(p.x, get_height(p.x, p.y), p.y)))
		grass_colors.append(Color("237a43").lerp(Color("3c9a55"), _rng.randf()))
	for grove in GROVES:
		var center: Vector2 = grove[0]
		var extents: Vector2 = grove[1]
		for i in 700:
			var p := center + Vector2(_rng.randf_range(-extents.x, extents.x), _rng.randf_range(-extents.y, extents.y))
			if distance_to_paths(p) < 1.5:
				continue
			var s := _rng.randf_range(1.1, 1.8)
			tall.append(Transform3D(Basis(Vector3.UP, _rng.randf() * TAU).scaled(Vector3(s * 0.9, s, s * 0.9)), Vector3(p.x, get_height(p.x, p.y), p.y)))
			tall_colors.append(Color("1f7f55").lerp(Color("35a06a"), _rng.randf()))
	var grass_mat := ShaderMaterial.new()
	grass_mat.shader = load("res://shaders/grass_sway.gdshader")
	grass_mat.set_shader_parameter("tip_color", Color("7fd89a"))
	_multimesh("Grass", tuft, grass, grass_colors, grass_mat, false)
	var tall_mat := ShaderMaterial.new()
	tall_mat.shader = load("res://shaders/grass_sway.gdshader")
	tall_mat.set_shader_parameter("tip_color", Color("7fe0b0"))
	tall_mat.set_shader_parameter("sway", 0.2)
	_multimesh("TallGrass", tuft, tall, tall_colors, tall_mat, false)


## Drifting fireflies (CPU particles work on every renderer).
func _build_fireflies() -> void:
	var root := Node3D.new()
	root.name = "Fireflies"
	add_child(root)
	var mesh := SphereMesh.new()
	mesh.radius = 0.06
	mesh.height = 0.12
	mesh.radial_segments = 6
	mesh.rings = 3
	mesh.material = MeshKit.toon(Color("d9ff7a"), {"unshaded": true})
	for spot in [CAMP, LAKE + Vector2(0, 16), GROVES[0][0], GROVES[1][0], RUINS]:
		var p: Vector2 = spot
		var fx := CPUParticles3D.new()
		fx.mesh = mesh
		fx.amount = 24
		fx.lifetime = 6.0
		fx.preprocess = 6.0
		fx.emission_shape = CPUParticles3D.EMISSION_SHAPE_BOX
		fx.emission_box_extents = Vector3(9, 1.2, 9)
		fx.gravity = Vector3.ZERO
		fx.direction = Vector3(0, 1, 0)
		fx.spread = 180.0
		fx.initial_velocity_min = 0.1
		fx.initial_velocity_max = 0.4
		fx.scale_amount_min = 0.6
		fx.scale_amount_max = 1.3
		fx.position = Vector3(p.x, get_height(p.x, p.y) + 1.8, p.y)
		root.add_child(fx)
